import { BaseModel } from '../../../_metronic/shared/crud-table';

export interface Product extends BaseModel {
  productCode: string,
  productName: string,
  categoryId: number,
  description: string,
  partnerID: number,
  isNew: number,
  isHot: number,
  viewCount: number,
  content: string,
  price: number,
  promotionPrice: number,
  video: string,
  status: number,
  seoAlias: string,
  seoKeyword: string,
  stock: number,
  imageUrl: string,
  rateDiscount: number,
  guarantee: number,
  productNameSlug: string,
  seoDescription: string,
  seoTitle: string,
  countRate: number,
  rate: number,
  createdDate: string,
  updatedDate: string,
  updatedUser: string,
  createdUser: string,
  productAttributes: any,
  productImages?: [],
  productTags: string
}

export interface ProductUpdate extends BaseModel {
  ProductId : number,
  ProductCode : string,
  ProductName : string,
  CategoryId  : number,
  Description : string,
  IsNew : number,
  IsHot : number,
  Content : string,
  Price : number,
  PromotionPrice  :number,
  Video : string,
  Stock : number,
  AttributeValueIds?: number[],
  Status : number,
  guarantee  : number,
  SeoDescription : string
  SeoTitle : string,
  SeoKeyword : string,
  ProductTags: string
}
